name: cli_animation
description: Animation cli that u can intergrated into your platform with rich animation
version: 1.0.1
repository: https://github.com/luchzin/cli-animation

environment:
  sdk: ^3.12.2

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
